### ISSUE TITLE
Monadic `lmapM`

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [Lysxia/profunctor-monad#3]
I found in [biparsing](https://github.com/BebeSparkelSparkel/biparsing) that a monadic `lmap` was very useful.

Is there an `lmapM :: (a -> m b) -> t m b c -> t m a c`?

**Comment by BebeSparkelSparkel** [comment]
It seems like Cofunctor may work here.

**Comment by Lysxia** [comment]
Indeed that's why I added `Cofunctor`, though I wonder if I really need the generality as opposed to just a mapping from `a -> Maybe b`

**Comment by BebeSparkelSparkel** [comment]
Actually, I have not been able to get `Cofunctor` to work correctly with this. It seems like I need

```haskell
class Cotrans p m | p -> m where colift :: (a -> m b) -> p b c -> p a c

newtype Fwd m u v = Fwd {unFwd :: m v}
instance Cotrans (Fwd m) m where
  colift = const coerce

newtype Bwd m u v = Bwd {unBwd :: u -> m v}
instance Monad m => Cotrans (Bwd m) m where
  colift f = Bwd . (>=>) f . unBwd
```

I'm not sure if this exists somewhere. Have you seen this before?

**Comment by BebeSparkelSparkel** [comment]
Sorry for the stupid question. `=:` accomplishes this.
